spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hsjnb.com:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: 不告诉你
    password: 不告诉你

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: warn
    com.hsjnb: info
  file:
    name: log/blog-pro.log

server:
  port: 80
